// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1q4cqKMDVgudxLkv8HlXFrHh741EsU5Y',
    appId: '1:712148588207:web:be23f8208a1cef4024e65a',
    messagingSenderId: '712148588207',
    projectId: 'bohdan-bats-portfolio',
    authDomain: 'bohdan-bats-portfolio.firebaseapp.com',
    storageBucket: 'bohdan-bats-portfolio.firebasestorage.app',
    measurementId: 'G-6QZJ0Y7WVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-oEs9EzgI9sICvEpLoVKlQ8_sPQKhgdc',
    appId: '1:712148588207:android:1991d8e339c3a06724e65a',
    messagingSenderId: '712148588207',
    projectId: 'bohdan-bats-portfolio',
    storageBucket: 'bohdan-bats-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2nlXuqHhO1hWfreDy98Ty0XSLVDIOlA',
    appId: '1:712148588207:ios:f8a8526609a76c0424e65a',
    messagingSenderId: '712148588207',
    projectId: 'bohdan-bats-portfolio',
    storageBucket: 'bohdan-bats-portfolio.firebasestorage.app',
    iosBundleId: 'bohdanbats.com.bohdanBatsPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk2nlXuqHhO1hWfreDy98Ty0XSLVDIOlA',
    appId: '1:712148588207:ios:f8a8526609a76c0424e65a',
    messagingSenderId: '712148588207',
    projectId: 'bohdan-bats-portfolio',
    storageBucket: 'bohdan-bats-portfolio.firebasestorage.app',
    iosBundleId: 'bohdanbats.com.bohdanBatsPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1q4cqKMDVgudxLkv8HlXFrHh741EsU5Y',
    appId: '1:712148588207:web:a61122decddf120924e65a',
    messagingSenderId: '712148588207',
    projectId: 'bohdan-bats-portfolio',
    authDomain: 'bohdan-bats-portfolio.firebaseapp.com',
    storageBucket: 'bohdan-bats-portfolio.firebasestorage.app',
    measurementId: 'G-0PXFYF6V1M',
  );
}
